<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Include="..\Common\L10n.cs" />
    <Compile Include="..\Common\L10n.en.cs" />
  </ItemGroup>
  <PropertyGroup>
    <AssemblyName>NoDurability</AssemblyName>
    <RootNamespace>NoDurability</RootNamespace>
    <Version>1.1.0</Version>
  </PropertyGroup>
</Project>
