<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Include="..\Common\L10n.cs" />
    <Compile Include="..\Common\L10n.en.cs" />
    <Compile Include="..\Common\ScrollGuard.cs" />
    <Compile Include="..\Common\ModWindows.cs" />
    <Compile Include="..\Common\Theme.cs" />
    <Compile Include="..\Common\Pad.cs" />
    <EmbeddedResource Include="Icons/*.png" LogicalName="%(Filename)%(Extension)" />
    <Reference Include="SoftReferenceableAssets"><HintPath>$(ValheimManaged)/SoftReferenceableAssets.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UIModule"><HintPath>$(ValheimManaged)/UnityEngine.UIModule.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
  <PropertyGroup>
    <AssemblyName>Guide</AssemblyName>
    <RootNamespace>Guide</RootNamespace>
    <Version>1.0.0</Version>
  </PropertyGroup>
</Project>
